# ??????
server.port=8082

# ?????
project.version=1.0.0-RC

# ????
logging.level.root=INFO
logging.level.jiangyuze.example.hollespringsamples=INFO

# ????
spring.application.name=HolleSpring-samples-test
