# ??????
server.port=8081

# ?????
project.version=1.0.0-SNAPSHOT

# ????
logging.level.root=INFO
logging.level.jiangyuze.example.hollespringsamples=DEBUG

# ????
spring.application.name=HolleSpring-samples-dev
