spring:
  datasource:
    url: jdbc:mysql://localhost:3306/json_import?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jyz20010930@A
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.example.springboot_week06.entity
  configuration:
    map-underscore-to-camel-case: true