CREATE TABLE IF NOT EXISTS `json_import` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `json_data` LONGTEXT NOT NULL COMMENT '原始 JSON 内容',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='JSON 导入数据表';
