# ??????
server.port=80

# ?????
project.version=1.0.0-RELEASE

# ????
logging.level.root=WARN
logging.level.jiangyuze.example.hollespringsamples=WARN

# ????
spring.application.name=HolleSpring-samples-prod
